export const mockUsers = [
  {
    id: "admin1",
    email: "admin@example.com",
    name: "Admin User",
    password: "admin123",
    role: "ADMIN" as const,
    totalLikes: 200,
  },
  {
    id: "user1",
    email: "user@example.com",
    name: "John Doe",
    password: "user123",
    role: "USER" as const,
    totalLikes: 45,
  },
  {
    id: "user2",
    email: "jane@example.com",
    name: "Jane Smith",
    password: "user123",
    role: "USER" as const,
    totalLikes: 150,
  },
  {
    id: "user3",
    email: "trouble@example.com",
    name: "Trouble Maker",
    password: "user123",
    role: "USER" as const,
    totalLikes: -5,
  },
  {
    id: "user4",
    email: "banned@example.com",
    name: "Banned User",
    password: "user123",
    role: "USER" as const,
    totalLikes: 15,
  },
  {
    id: "user5",
    email: "lisa@example.com",
    name: "Lisa Garcia",
    password: "user123",
    role: "USER" as const,
    totalLikes: 0,
  },
]